### ISSUE TITLE
Error updating firmware on Ubuntu

### ISSUE THREAD

**Issue by aulvi** [Jewelbots/arduino-library#13]
Hello! I'm running into an error attempting to update my Jewelbot's firmware.

```
Arduino: 1.6.13 (Linux), Board: "Jewelbots Firmware Update"

java.io.IOException: Cannot run program "/home/caitlin/.arduino15/packages/Jewelbots_Firmware_Update/hardware/JWBFirmware/1.0.0/JWBLoader_linux": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:11)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:207)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
	at processing.app.SketchController.upload(SketchController.java:709)
	at processing.app.SketchController.exportApplet(SketchController.java:682)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2189)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 10 more
An error occurred while uploading the sketch

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

Sure enough, the file doesn't exist:
```
caitlin@caitlin-IdeaPad-S210-Touch:~/.arduino15/packages/Jewelbots_Firmware_Update/hardware/JWBFirmware/1.0.0$ ls -l
total 13492
-rw-r--r-- 1 caitlin caitlin     393 Nov 22 10:09 boards.txt
drwxr-xr-x 3 caitlin caitlin    4096 Nov 22 10:09 cores
-rw-r--r-- 1 caitlin caitlin 7712620 Nov 22 10:09 JWBLoader.exe
-rwxr-xr-x 1 caitlin caitlin 5900351 Nov 22 10:09 JWBLoader_osx
-rw-r--r-- 1 caitlin caitlin  124436 Nov 22 10:09 JWB_update_1_01a.zip
-rw-r--r-- 1 caitlin caitlin   48722 Nov 22 10:09 JWB_update_1_01b.zip
-rwxr-xr-x 1 caitlin caitlin     247 Nov 22 10:09 JWB_Update_mac.sh
-rw-r--r-- 1 caitlin caitlin     257 Nov 22 10:09 JWB_Update_win.bat
-rw-r--r-- 1 caitlin caitlin    3941 Nov 22 10:09 platform.txt
-rw-r--r-- 1 caitlin caitlin       0 Nov 22 10:09 programmers.txt
drwxr-xr-x 3 caitlin caitlin    4096 Nov 22 10:09 variants
```

More details about my system:

```
caitlin@caitlin-IdeaPad-S210-Touch:/$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
caitlin@caitlin-IdeaPad-S210-Touch:/$ uname -a
Linux caitlin-IdeaPad-S210-Touch 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Please let me know if I can answer any questions or be of any further help.

**Comment by SaraJo** [comment]
Thank you! We are looking into this.

**Comment by davison-sm** [comment]
Thanks again for your interest in Jewelbots!

Preliminary Linux support has been added to both our Arduino Library and Arduino Firmware Update repositories.

To test them out, just head back to Tools->Boards->Board Manager and "Remove" the existing installed versions.  When the removal process is finished, hit "Install" to download and install the updated version.

Note this Linux tools were built and tested on Ubuntu 16.04 only.  Other versions may not function properly.  Also, in linux the user account has to be part of the "dialout" group to access the USB port through Arduino.  Please see the detailed instructions on www.jewelbots.com/go for adding that permission.

**Comment by aulvi** [comment]
Confirmed this works for us now, thanks everyone!

Curious though, I thought I saw Ubuntu instructions posted on the `/go` page but now they're missing. Was I looking somewhere else or am I completely mistaken? In any event we were able to get things up and running, thanks again!
